/**
 * 引用 Android 系统库，示例如下：
 * import { Context } from "android.content.Context";
 * [可选实现，按需引入]
 */
// @ts-ignore
import {CourseParams, DashboardInsightResponse, DashboardResultWrapper, DeleteCourse, RestoreCourse} from "./types.uts"
// @ts-ignore
import Manager from "com.feifan.fuckingnjit.utils.Manager"
// @ts-ignore
import CoreInitializer from "com.feifan.fuckingnjit.utils.CoreInitializer"
// @ts-ignore
import AppConfig from 'com.feifan.fuckingnjit.utils.AppConfig'
// @ts-ignore
import SystemActionHelper from "com.feifan.fuckingnjit.utils.system.SystemActionHelper"
// @ts-ignore
import DecisionFacade from 'com.feifan.fuckingnjit.decision.DecisionFacade'
// @ts-ignore
import DataSyncService from 'com.feifan.fuckingnjit.service.DataSyncService'

// @ts-ignore
import CurriculumsWidget from 'com.feifan.fuckingnjit.widget.CurriculumsWidget'
// @ts-ignore
import PortalManager from "com.feifan.fuckingnjit.utils.network.wifiauth.PortalManager";

function parseUTSResponse(data: string): UTSJSONObject{
	try {
    	// 使用 JSON.parseObject 进行解析
		const result = JSON.parse(data);
    	
    	// 检查解析结果是否为空（可能是因为 JSON 字符串格式错误）
    	if (result === null) {
    	    throw new Error("数据解析失败：JSON格式可能不正确或数据为空");
    	}
    	return result as UTSJSONObject;
		// @ts-ignore
	} catch (e: Error) {
		console.log(e)
    	return new UTSJSONObject()
    }
}

export class Core {

	public showToast(str : string) {
		// @ts-ignore
		SystemActionHelper.showToast(UTSAndroid.getAppContext()!, str);
	}

	public startLogin(relogin : boolean) {
		// @ts-ignore
		SystemActionHelper.startLogin(UTSAndroid.getAppContext()!, relogin)
	}


	public async getCurriculum(refresh: boolean): Promise<UTSJSONObject> {
		// @ts-ignore
		const data = await Manager.getUserManager().getCurriculum(UTSAndroid.getAppContext()!, refresh).toJSONString();
		const tmp = parseUTSResponse(data)
		if(tmp.contains('code') && tmp['code'] == 200.0){
			return tmp['data']
		}else{
			this.showToast("课表获取失败")
			return new UTSJSONObject()
		}
	}

	public getAllUsers() : string {
		// @ts-ignore
		return Manager.getUserManager().getAllUsers(UTSAndroid.getAppContext()!)
	}

	public setCurrentUser(id : string) {
		// @ts-ignore
		return Manager.getUserManager().setCurrentUser(UTSAndroid.getAppContext()!, id)
	}

	public async deleteUser(id : string) : Promise<boolean> {
		// @ts-ignore
		return await Manager.getUserManager().deleteUser(UTSAndroid.getAppContext()!, id)
	}

	public async getEmptyClassrooms(dateRange: string, coursePeriod: string, buildingId: string): Promise<UTSJSONObject> {
		// @ts-ignore
		const data = await Manager.getWebService().getEmptyClassrooms(UTSAndroid.getAppContext()!, dateRange, coursePeriod, buildingId).toJSONString();
		const tmp = parseUTSResponse(data)
		if(tmp.contains('code') && tmp['code'] == 200.0){
			return tmp['data']
		}else{
			this.showToast("空教室获取失败")
			return new UTSJSONObject()
		}
	}

	public async getSorces(xnm: String, xqm: String, refresh: boolean): Promise<UTSJSONObject> {
		// @ts-ignore
		const data = await Manager.getUserManager().getUserScores(UTSAndroid.getAppContext()!, xnm, xqm, refresh).toJSONString();
		const tmp = parseUTSResponse(data)
		if(tmp.contains('code') && tmp['code'] == 200.0){
			return tmp.toJSONString() // 直接返回data，或者tmp['data']会
		}else{
			this.showToast("成绩获取失败")
			return new UTSJSONObject()
		}
	}

	public async getSorcesDetail(classId : string, schoolYear : string, semester : string, courseName : string) : Promise<UTSJSONObject> {
		// @ts-ignore
		const data = await Manager.getWebService().getSorcesDetail(UTSAndroid.getAppContext()!, classId, schoolYear, semester, courseName).toJSONString();
		return parseUTSResponse(data)
	}
	// public async getNoticeInformation() : Promise<UTSJSONObject> {
	// 	const data = await Manager.getWebService().getNoticeInformation().toJSONString();
	// 	return parseUTSResponse(data)
	// }

	public async getAcademicProgress(refresh : boolean) : Promise<UTSJSONObject> {
		// @ts-ignore
		const data = await Manager.getUserManager().getAcademicProgress(UTSAndroid.getAppContext()!,refresh).toJSONString();
		return parseUTSResponse(data)
	}

	public async saveCourse(data: CourseParams): Promise<UTSJSONObject> {
		// @ts-ignore
		const result = await Manager.getWebService().saveCourse(UTSAndroid.getAppContext()!,data.course, data.hideRule).toJSONString();
		return parseUTSResponse(result)
	}
	public async deleteCourse(data: DeleteCourse): Promise<UTSJSONObject> {
		// @ts-ignore
		const result = await Manager.getWebService().deleteCourse(UTSAndroid.getAppContext()!,data.courseId, data.isSystem, data.day,data.start).toJSONString();
		return parseUTSResponse(result)
	}
	public async restoreCourse(data: RestoreCourse): Promise<UTSJSONObject> {
		// @ts-ignore
		const result = await Manager.getWebService().restoreCourse(UTSAndroid.getAppContext()!,data.courseId, data.day,data.start).toJSONString();
		return parseUTSResponse(result)
	}
	public getDate() : string {
		// @ts-ignore
		return Manager.getWebService().getDate(UTSAndroid.getAppContext()!)
	}
	public createWidget() : string {
		// @ts-ignore
		return (new CurriculumsWidget(UTSAndroid.getAppContext()!)).createWidget()
	}
	public getWidgetPermission() {
		// @ts-ignore
		return (new CurriculumsWidget(UTSAndroid.getAppContext()!)).getPermission()
	}
	public isWidgetAlreadyCreated() : boolean {
		// @ts-ignore
		return (new CurriculumsWidget(UTSAndroid.getAppContext()!)).isWidgetAlreadyCreated()
	}

	public switchStatus(status : boolean) : void {
		// @ts-ignore
		PortalManager.switchStatus(UTSAndroid.getAppContext()!,status)
		// return (new WifiAuth(UTSAndroid.getAppContext()!)).createWidget()
	}

	public isEnabled() : boolean {
		// @ts-ignore
		return PortalManager.isEnabled(UTSAndroid.getAppContext()!)
	}
	public setWifiAuthType(type : string) {

		AppConfig.setWifiAuthType(type)
	}
	public getWifiAuthType() : string {
		return AppConfig.getWifiAuthType()
	}

	public goHome() {
		// @ts-ignore
		SystemActionHelper.goHome(UTSAndroid.getAppContext()!)
	}


	public setPasswordStorageEnabled(enable : boolean) {
		Manager.getUserManager().setPasswordStorageEnabled(enable)
	}

	public isPasswordStorageEnabled() : boolean {
		return Manager.getUserManager().isPasswordStorageEnabled()
	}

	public async updateApp(url : string) : Promise<boolean> {
		// @ts-ignore
		return await SystemActionHelper.updateApp(UTSAndroid.getAppContext()!,url)
	}
	public checkInstallPackagePermission() : boolean {
		// @ts-ignore
		return Manager.getPermissionsManager(UTSAndroid.getUniActivity()!).checkRequestInstallPackage()
	}
	public requestInstallPackage() : Promise<boolean> {
		return new Promise((resolve, reject) => {
			// @ts-ignore
			Manager.getPermissionsManager(UTSAndroid.getUniActivity()!).requestRequestInstallPackage((isGranted: boolean) => {
				if (isGranted) {
					resolve(true)
				} else {
					reject(false)
				}
			})
		})
	}

	public isSmartUpdate() : boolean {
		// @ts-ignore
		return Manager.getPermissionsManager(UTSAndroid.getUniActivity()!).isSmartUpdate()
	}

	public setSmartUpdate(isSmart: boolean){
		// @ts-ignore
		Manager.getPermissionsManager(UTSAndroid.getUniActivity()!).setSmartUpdate(isSmart)
	}

	public checkRecordAudio() : boolean {
		// @ts-ignore
		return Manager.getPermissionsManager(UTSAndroid.getUniActivity()!).checkRecordAudio()
	}

	public requestRecordAudio() : Promise<boolean>{
		// @ts-ignore
		return new Promise((resolve, reject) => {
			// @ts-ignore
			Manager.getPermissionsManager(UTSAndroid.getUniActivity()!).requestRecordAudio((isGranted: boolean) => {
				if (isGranted) {
					resolve(true)
				} else {
					reject(false)
				}
			})
		})
	}

	public checkNotification() : boolean {
		// @ts-ignore
		return Manager.getPermissionsManager(UTSAndroid.getUniActivity()!).checkNotification()
	}

	public requestNotificationService() : Promise<boolean>{
		return new Promise((resolve, reject) => {
			// @ts-ignore
			Manager.getPermissionsManager(UTSAndroid.getUniActivity()!).requestNotificationServicePermission((isGranted: boolean) => {
				if (isGranted) {
					resolve(true)
				} else {
					reject(false)
				}
			})
		})
	}

	// public checkPackageUsageStats() : boolean {
	// 	return Manager.getPermissionsManager().checkPackageUsageStats()
	// }
	//
	// public requestUsageStats() : Promise<boolean>{
	// 	return new Promise((resolve, reject) => {
	// 		Manager.getPermissionsManager().requesPackageUsageStats((isGranted: boolean) => {
	// 			if (isGranted) {
	// 				resolve(true)
	// 			} else {
	// 				reject(false)
	// 			}
	// 		})
	// 	})
	// }

	public checkScheduleExactAlarm() : boolean {
		// @ts-ignore
		return Manager.getPermissionsManager(UTSAndroid.getUniActivity()!).checkScheduleExactAlarm()
	}

	public requestExactAlarm() : Promise<boolean>{
		return new Promise((resolve, reject) => {
			// @ts-ignore
			Manager.getPermissionsManager(UTSAndroid.getUniActivity()!).requestScheduleExactAlarm((isGranted: boolean) => {
				if (isGranted) {
					resolve(true)
				} else {
					reject(false)
				}
			})
		})
	}

	public requestKeepAliveNormalPermissions() : Promise<Array<string>>{
		return new Promise((resolve, reject) => {
			// @ts-ignore
			Manager.getPermissionsManager(UTSAndroid.getUniActivity()!).requestKeepAliveNormalPermissions((isGranted: boolean,list: List<String>) => {
				if (isGranted) {
					resolve(Array<string>())
				} else {
					// @ts-ignore
					reject(Array.fromNative(list))
				}
			})
		})
	}

	public isIgnoringBatteryOptimizations() : boolean {
		// @ts-ignore
		return Manager.getPermissionsManager(UTSAndroid.getUniActivity()!).isIgnoringBatteryOptimizations()
	}

	public requestIgnoreBatteryOptimizations(){
		// @ts-ignore
			Manager.getPermissionsManager(UTSAndroid.getUniActivity()!).requestIgnoreBatteryOptimizations()
	}

	public isAccessibilitySettingsOn() : boolean {
		// @ts-ignore
		return Manager.getPermissionsManager(UTSAndroid.getUniActivity()!).isAccessibilitySettingsOn()
	}

	public requestAccessibilityPermission(){
		// @ts-ignore
		Manager.getPermissionsManager(UTSAndroid.getUniActivity()!).requestAccessibilityPermission()
	}

	public async initYiBan(mobile: string, password: string): Promise<UTSJSONObject>{
		// @ts-ignore
		const data = await CoreInitializer.initYiBan(UTSAndroid.getAppContext()!,mobile,password).toJSONString();
		return parseUTSResponse(data)
	}

	public async refreshSleepData() {
		await DataSyncService.uploadAndClearData();
	}

	public switchAppMode(mode:string){
		// @ts-ignore
		DecisionFacade.switchAppMode(mode);
	}

	// /**
	//  * 获取智能决策看板数据
	//  */
	public async getDashboardInsight(): Promise<DashboardInsightResponse> {
		// @ts-ignore
		const data = await DecisionFacade.getDashboardInsight(UTSAndroid.getAppContext()!).toJSONString();
		const tmp = parseUTSResponse(data)
		if(tmp.contains('code') && tmp['code'] == 200.0){
			return tmp['data']
		}else{
			this.showToast("健康数据获取失败")
			return {}
		}
	}
}
