/**
 * 引用 Android 系统库，示例如下：
 * import { Context } from "android.content.Context";
 * [可选实现，按需引入]
 */
import Manager from "com.feifan.fuckingnjit.utils.Manager"
import DemoMainWidget from 'com.feifan.fuckingnjit.widget.DemoMainWidget'
import WifiAuth from "com.feifan.fuckingnjit.widget.WifiAuth";
type CourseParams = {
    course: string
    hideRule?: string
}
type deleteCourse = {
	courseId: string
	isSystem: boolean
	day?: Int
	start?: Int
}
type restoreCourse = {
	courseId: string
	day: Int
	start: Int
}

export class Core {

	public showToast(str : string) {
		Manager.showToast(str);
	}

	public startLogin(relogin : boolean) {
		Manager.startLogin(relogin)
	}

	public async getCurriculum(refresh : boolean) : Promise<UTSJSONObject> {
		return JSON.parse<UTSJSONObject>(await Manager.getUserManager().getCurriculum(refresh)) ?? {}
	}

	public getAllUsers() : string {
		return Manager.getUserManager().getAllUsers()
	}

	public setCurrentUser(id : string) {
		return Manager.getUserManager().setCurrentUser(id)
	}

	public async deleteUser(id : string) : Promise<boolean> {
		return await Manager.getUserManager().deleteUser(id)
	}

	public async getEmptyClassrooms(dateRange : string, coursePeriod : string, buildingId : string) : Promise<string> {
		return await Manager.getWebService().getEmptyClassrooms(dateRange, coursePeriod, buildingId)
	}
	public async getSorces(xnm:String,xqm:String,refresh : boolean) : Promise<string> {
		return await Manager.getUserManager().getUserScores(xnm,xqm,refresh)
	}
	
	public async getSorcesDetail(classId : string, schoolYear : string, semester : string, courseName : string) : Promise<string> {
		return await Manager.getWebService().getSorcesDetail(classId, schoolYear, semester, courseName)
	}
	public async getNoticeInformation() : Promise<string> {
		return await Manager.getWebService().getNoticeInformation()
	}

	public async getAcademicProgress(refresh : boolean) : Promise<string> {
		return await Manager.getUserManager().getAcademicProgress(refresh)
	}
	
	public saveCourse(data: CourseParams): UTSJSONObject {
		return JSON.parse<UTSJSONObject>(
			Manager.getWebService().saveCourse(data.course, data.hideRule).toJSONString()
		) ?? {}
	}
	public deleteCourse(data: deleteCourse): UTSJSONObject {
		return JSON.parse<UTSJSONObject>(
			Manager.getWebService().deleteCourse(data.courseId, data.isSystem, data.day,data.start).toJSONString()
		) ?? {}
	}
	public restoreCourse(data: restoreCourse): UTSJSONObject {
		return JSON.parse<UTSJSONObject>(
			Manager.getWebService().restoreCourse(data.courseId, data.day,data.start).toJSONString()
		) ?? {}
	}
	public getDate() : string {
		return Manager.getWebService().getDate()
	}
	public createWidget() : string {
		return (new DemoMainWidget(UTSAndroid.getAppContext()!)).createWidget()
	}
	public getWidgetPermission() {
		return (new DemoMainWidget(UTSAndroid.getAppContext()!)).getPermission()
	}
	public isWidgetAlreadyCreated() : boolean {
		return (new DemoMainWidget(UTSAndroid.getAppContext()!)).isWidgetAlreadyCreated()
	}
	
	public createWifiAuthWidget() : string {
		return (new WifiAuth(UTSAndroid.getAppContext()!)).createWidget()
	}
	public getWifiAuthWidgetPermission() {
		return (new WifiAuth(UTSAndroid.getAppContext()!)).getPermission()
	}
	public isWifiAuthWidgetAlreadyCreated() : boolean {
		return (new WifiAuth(UTSAndroid.getAppContext()!)).isWidgetAlreadyCreated()
	}
	public setWifiAuthTupe(type : string) {
		Manager.setWifiAuthTupe(type)
	}
	public getWifiAuthTupe() : string {
		return Manager.getWifiAuthTupe()
	}

	public goHome() {
		Manager.goHome()
	}


	public setPasswordStorageEnabled(enable : boolean) {
		Manager.getUserManager().setPasswordStorageEnabled(enable)
	}

	public isPasswordStorageEnabled() : boolean {
		return Manager.getUserManager().isPasswordStorageEnabled()
	}

	public getSemesterStartDate() : string {
		return Manager.getSemesterStartDate()
	}

	public async updateApp(url : string) : Promise<boolean> {
		return await Manager.updateApp(url)
	}
	public checkOverlayWindowPermission() : boolean {
		return Manager.getPermissionsManager().checkOverlayWindowPermission()
	}
	public requestOverlayWindowPermission() : Promise<boolean> {
		return new Promise((resolve, reject) => {
			Manager.getPermissionsManager().requestOverlayWindowPermission((isGranted: boolean) => {
				if (isGranted) {
					resolve(true)
				} else {
					reject(false)
				}
			})
		})
	}
	public checkRequestInstallPackagePermission() : boolean {
		return Manager.getPermissionsManager().checkRequestInstallPackagePermission()
	}
	public requestRequestInstallPackagePermission() : Promise<boolean> {
		return new Promise((resolve, reject) => {
			Manager.getPermissionsManager().requestRequestInstallPackagePermission((isGranted: boolean) => {
				if (isGranted) {
					resolve(true)
				} else {
					reject(false)
				}
			})
		})
	}

	public isSmartUpdate() : boolean {
		return Manager.getPermissionsManager().isSmartUpdate()
	}
	public setSmartUpdate(isSmart: boolean){
		Manager.getPermissionsManager().setSmartUpdate(isSmart)
	}
	public setLocalCurriculums(data : string) {
		Manager.setLocalCurriculums(data)
	}
	public modifyLocalCurriculums(keys : string) {
		Manager.modifyLocalCurriculums(keys)
	}
	public reSetLocalCurriculums() {
		Manager.reSetLocalCurriculums()
	}
}

/**
 * 更多插件开发的信息详见：https://uniapp.dcloud.net.cn/plugin/uts-plugin.html
 */