import UMConfigure from "com.umeng.commonsdk.UMConfigure";

import MobclickAgent from  "com.umeng.analytics.MobclickAgent";
import PageMode from "com.umeng.analytics.MobclickAgent.PageMode"
import HashMap from "java.util.HashMap";
import Map from "java.util.Map";
import OnGetOaidListener from  "com.umeng.commonsdk.listener.OnGetOaidListener";

 const preUMInit=function(key:string,channel:string){
	 UMConfigure.preInit(UTSAndroid.getAppContext()!,key,channel);
}

// export const UMinit=function(){
// 	// umInitConfig: const UmInitConfig =new UmInitConfig();
// 	//  umInitConfig.UMinit(UTSAndroid.getAppContext()!);
// 	 MobclickAgent.setPageCollectionMode(MobclickAgent.PageMode.Manual);
// 	 UMConfigure.setProcessEvent(true);//支持多进程打点

// }


export const initUM=function(key:string,channel:string){
	  UMConfigure.setLogEnabled(true);
	  preUMInit("67d77c8948ac1b4f87e98e5f","android")
	  UMConfigure.init(UTSAndroid.getAppContext()!,key,channel,UMConfigure.DEVICE_TYPE_PHONE,"");
	  MobclickAgent.setPageCollectionMode(PageMode.MANUAL);
	  UMConfigure.setProcessEvent(true);//支持多进程打点
}

export const UMonKillProcess=function(){
	 MobclickAgent.onKillProcess(UTSAndroid.getAppContext()!);
}

export const UMonProfileSignIn=function(ID:string){
	 MobclickAgent.onProfileSignIn(ID);
}

export const UMonProfileSignIns=function(Provider:string , ID:string){
	 MobclickAgent.onProfileSignIn(Provider,ID);
}

export const UMonProfileSignOff=function(){
	 MobclickAgent.onProfileSignOff();
}

export const UMuserProfileMobile=function(mobile:string){
	MobclickAgent.userProfileMobile(mobile);
}


export const UMuserProfileEMail=function(email:string){
	MobclickAgent.userProfileEMail(email);
}




export const UMuserProfile=function(key:string,value:string){
	MobclickAgent.userProfile(key,value);
}


export const UMonPageStart=function(viewName:string){
	    MobclickAgent.onPageStart(viewName); 
};


export const UMonPageEnd=function(viewName:string){
	    MobclickAgent.onPageEnd(viewName); 
};




export const UMonEventObject=function(eventID:string,key:string[],value:string[]){
	var maps= emptyMap<String,String>().toMutableMap();
	for(var i =0;i< key.length;i++){
		maps[key[i.toInt()]]=value[i.toInt()];
	}
	MobclickAgent.onEventObject(UTSAndroid.getAppContext()!,eventID, maps.toMap());
}



export const UMsubmitPolicyGrantResult=function(flag:boolean ){
	UMConfigure.submitPolicyGrantResult(UTSAndroid.getAppContext()!, flag);
}



export const UMenableImsiCollection=function(flag:boolean){
	UMConfigure.enableImsiCollection(flag);
}


export const UMenableIccidCollection=function(flag:boolean){
	UMConfigure.enableIccidCollection(flag);
}

export const UMenableImeiCollection=function(flag:boolean){
	UMConfigure.enableImeiCollection(flag);
}

export const UMenableWiFiMacCollection=function(flag:boolean){
	UMConfigure.enableWiFiMacCollection(flag);
}
export const onUMgetOaid=function(callback:(oaid:string)=>void){
	class MyOnGetOaidListener implements OnGetOaidListener{
		override  onGetOaid( oaid:string):void{
			callback(oaid);
		} 
	}
	UMConfigure.getOaid(UTSAndroid.getAppContext()!,new MyOnGetOaidListener());
}



export const getUMIDString=function():string{
	return UMConfigure.getUMIDString(UTSAndroid.getAppContext()!);
}





